version: "3.7"
services:
  cloak-server:
    build:
      context: .
      dockerfile: Dockerfile-cloak-server
    container_name: cloak-server
    ports:
      - "4433:4433"
    environment:
      CLOAK_BYPASS_UID: $CLOAK_BYPASS_UID
      CLOAK_REDIR_ADDR: $CLOAK_REDIR_ADDR
      CLOAK_PRIVATE_KEY: $CLOAK_PRIVATE_KEY
      CLOAK_BIND_PORTS: $CLOAK_BIND_PORTS
    restart: unless-stopped

  shadowsocks-server:
    build:
      context: .
      dockerfile: Dockerfile-shadowsocks-server
    container_name: shadowsocks-server
    ports:
      - "8399:8399"
    environment:
      SS_SERVER_IP: $SS_SERVER_IP
      SS_SERVER_PASSWORD: $SS_SERVER_PASSWORD
      SS_ENC_METHOD: $SS_ENC_METHOD
    restart: unless-stopped
