version: "3.7"

networks:
  rpi-docker_ipv4_net:
    external: true

services:
  cloak-server:
    build:
      context: .
      dockerfile: Dockerfile-cloak-server
    container_name: cloak-server
    environment:
      CLOAK_BYPASS_UID: $CLOAK_BYPASS_UID
      CLOAK_REDIR_ADDR: $CLOAK_REDIR_ADDR
      CLOAK_PRIVATE_KEY: $CLOAK_PRIVATE_KEY
      CLOAK_BIND_PORTS: $CLOAK_BIND_PORTS
    networks:
      - rpi-docker_ipv4_net
    labels:
      - "traefik.http.routers.secureroute.rule=HostRegexp(`*`)"
      - "traefik.http.routers.secureroute.entrypoints=websecure"
      - "traefik.http.routers.secureroute.tls=true"
      - "traefik.http.routers.secureroute.priority=1000"
      # - "traefik.http.routers.secureroute.service=gitlab"
      - "traefik.http.services.cloak-server.loadbalancer.server.port=443"
      - "traefik.enable=true"
    restart: unless-stopped

  shadowsocks-server:
    build:
      context: .
      dockerfile: Dockerfile-shadowsocks-server
    container_name: shadowsocks-server
    environment:
      SS_SERVER_IP: $SS_SERVER_IP
      SS_SERVER_PASSWORD: $SS_SERVER_PASSWORD
      SS_ENC_METHOD: $SS_ENC_METHOD
    networks:
      - rpi-docker_ipv4_net
    restart: unless-stopped
