FROM alpine:latest
    
ENV CLOAK_BYPASS_UID null
ENV CLOAK_REDIR_ADDR 1.0.0.1
ENV CLOAK_PRIVATE_KEY null
ENV CLOAK_BIND_PORTS '\":443\",\":80\"'

EXPOSE 4433/tcp

RUN mkdir -p /app
WORKDIR /app

COPY ./scripts/entrypoint-cloak-server.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

COPY ./bin/ck-server-linux-arm64-v2.9.0 /app/ck-server
RUN chmod +x /app/ck-server

COPY ./config/shadowsocks_config.json /app/config.json

ENTRYPOINT [ "./entrypoint.sh" ]
CMD [ "/app/ck-server" , "-c" , "/app/config.json" ]
