FROM ghcr.io/shadowsocks/ssserver-rust:latest

ENV SS_SERVER_IP 0.0.0.0
ENV SS_ENC_METHOD AEAD_CHACHA20_POLY1305
ENV SS_SERVER_PASSWORD $PASSWORD

EXPOSE 8399

RUN mkdir -p /app
WORKDIR /app

COPY scripts/entrypoint-shadowsocks-server.sh /app/entrypoint.sh
RUN chmod +x entrypoint.sh

COPY config/shadowsocks_config.json /app/config.json

ENTRYPOINT [ "./entrypoint.sh" ]
CMD [ "ssserver", "-a", "nobody", "-c", "/app/config.json" ]
