version: "3.7"
services:
  # cloak-server:
  #   image: freddykrum/cloaksocks:ck-server
  #   ports:
  #     - "$BINDPORT:$BINDPORT"
  #   environment:
  #     LOCAL_IP:     $LOCAL_IP
  #     LOCAL_PORT:   $LOCAL_PORT
  #     METHOD:       shadowsocks
  #     BYPASSUID:    $BYPASSUID
  #     REDIRADDR:    $REDIRADDR
  #     PRIVATEKEY:   $PRIVATEKEY
  #     ADMINUID:     $ADMINUID
  #     PUBLICKEY:    $PUBLICKEY
  #     ENCRYPTION:   $ENCRYPTION
  #     PASSWORD:     $PASSWORD
  #     BINDPORT:     $BINDPORT
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: always

  shadowsocks-server:
    build:
      context: .
      dockerfile: Dockerfile-shadowsocks-server
    container_name: shadowsocks-server
    ports:
      - "8399:8399"
    environment:
      SS_SERVER_IP: $SS_SERVER_IP
      SS_SERVER_PASSWORD: $SS_SERVER_PASSWORD
      SS_ENC_METHOD: $SS_ENC_METHOD
    restart: unless-stopped
